"""empty message

Revision ID: 2daf89c272ae
Revises: f2e7d4106f23
Create Date: 2020-01-31 21:26:51.464054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daf89c272ae'
down_revision = 'f2e7d4106f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_genre_relationship', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('artist_genre_relationship', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_genre_relationship', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('venue_genre_relationship', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('venue_genre_relationship', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_genre_relationship', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_genre_relationship', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_genre_relationship', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('venue_genre_relationship', 'id')
    op.alter_column('artist_genre_relationship', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_genre_relationship', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artist_genre_relationship', 'id')
    # ### end Alembic commands ###
