"""empty message

Revision ID: 76fb27b592d5
Revises: 905d0e4cb13e
Create Date: 2020-01-31 21:07:00.431037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fb27b592d5'
down_revision = '905d0e4cb13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genre_relationship_artist_id_fkey', 'artist_genre_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genre_relationship', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_genre_relationship', type_='foreignkey')
    op.create_foreign_key('artist_genre_relationship_artist_id_fkey', 'artist_genre_relationship', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
