"""empty message

Revision ID: 905d0e4cb13e
Revises: 71f43d307da7
Create Date: 2020-01-28 19:51:55.144132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905d0e4cb13e'
down_revision = '71f43d307da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
