"""Add missing database fields to Artist and Venue models.

Revision ID: bdf9ededb5b4
Revises: cdf9210409b3
Create Date: 2020-01-27 18:39:13.626484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf9ededb5b4'
down_revision = 'cdf9210409b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'slug')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'slug')
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###
