"""Insert genre tables and relationship to venue and artist; 
insert data for available genres.

Revision ID: cdf9210409b3
Revises: 67ed0198ca6c
Create Date: 2020-01-26 11:33:11.123734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer
import urllib.parse

# Sanitize genre names for slugs
# Source = https://www.peterbe.com/plog/fastest-python-function-to-slugify-a-string

def slugify(text):
    """
    Turn the text content of a header into a slug for use in an ID
    """
    non_url_safe = ['"', '#', '$', '%', '&', '+',
                ',', '/', ':', ';', '=', '?',
                '@', '[', '\\', ']', '^', '`',
                '{', '|', '}', '~', "'"]
    non_safe = [c for c in text if c in non_url_safe]
    if non_safe:
        for c in non_safe:
            text = text.replace(c, '')
    # Strip leading, trailing and multiple whitespace, convert remaining whitespace to _
    text = u'_'.join(text.split())
    return text.lower()

# revision identifiers, used by Alembic.
revision = 'cdf9210409b3'
down_revision = '67ed0198ca6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('artist_genre_relationship',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table('venue_genre_relationship',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    op.drop_column('Artist', 'genres')

    # Create an ad-hoc table to use for the insert statement.
    genres_table = table('Genre',
        column('id', Integer),
        column('name', String),
        column('slug', String)
    )

    genre_list = [
        'Alternative',
        'Blues', 
        'Classical',
        'Country', 
        'Electronic', 
        'Folk', 
        'Funk', 
        'Hip-Hop', 
        'Heavy Metal', 
        'Instrumental',
        'Jazz',
        'Musical Theatre', 
        'Pop', 
        'Punk',
        'R&B',
        'Reggae',
        'Rock n Roll',
        'Soul', 
        'Other'
    ]

    id_index = 0
    genre_list_insert = []
    for genre in genre_list:
        id_index+=1
        genre_list_insert.append({
            'id': id_index,
            'name': genre,
            'slug': slugify(genre)
        })

    op.bulk_insert(genres_table, genre_list_insert)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('venue_genre_relationship')
    op.drop_table('artist_genre_relationship')
    op.drop_table('Genre')
    # ### end Alembic commands ###
