"""empty message

Revision ID: f2e7d4106f23
Revises: 76fb27b592d5
Create Date: 2020-01-31 21:08:11.679867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e7d4106f23'
down_revision = '76fb27b592d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genre_relationship_venue_id_fkey', 'venue_genre_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre_relationship', 'Venue', ['venue_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre_relationship', type_='foreignkey')
    op.create_foreign_key('venue_genre_relationship_venue_id_fkey', 'venue_genre_relationship', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
